// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXu1b3CahVmItQFiTofGpoIb_vZi7Vwoo',
    appId: '1:332583301773:web:7604466e3b2d385e4b68c4',
    messagingSenderId: '332583301773',
    projectId: 'sanfood-d0c93',
    authDomain: 'sanfood-d0c93.firebaseapp.com',
    storageBucket: 'sanfood-d0c93.appspot.com',
    measurementId: 'G-QJY7ZZD52Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATK-D6SPpTp5n61oxT7WJHsNLqqniPv7I',
    appId: '1:332583301773:android:44f30fc5da600c7c4b68c4',
    messagingSenderId: '332583301773',
    projectId: 'sanfood-d0c93',
    storageBucket: 'sanfood-d0c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DZlGhzU78PZMYouoRCHYi1DKLutDvNo',
    appId: '1:332583301773:ios:c48579b43025ee964b68c4',
    messagingSenderId: '332583301773',
    projectId: 'sanfood-d0c93',
    storageBucket: 'sanfood-d0c93.appspot.com',
    iosClientId: '332583301773-n68lcjacr4af2ims5q6072ovtbmo96aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanfood',
  );
}
